#!/usr/bin/env python3
"""The inbox pipeline's suite: glTF reading, the camera, the bake, the gates.

    python3 tests/test_pipeline.py

Python rather than GDScript because none of it needs an engine -- the pipeline
runs before Godot is involved, and a failure here should be readable without
waiting for an import pass. `tools/ci.sh test` runs this first, then the
GDScript suite, so one command is still the whole gate.

The model under test is generated by tests/fixtures/make_model.py rather than
committed, because a binary blob is a thing nobody can review in a diff.
"""

import contextlib
import io
import math
import os
import shutil
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, os.path.join(ROOT, "tests/fixtures"))

import glb
import inbox
import packs
import pixel
import sprite_bake
import make_model

FAILURES = []
CHECKS = [0]


def check(condition, message):
    CHECKS[0] += 1
    if not condition:
        FAILURES.append(message)


def near(a, b, tolerance=1e-6):
    return abs(a - b) <= tolerance


@contextlib.contextmanager
def quiet():
    """Swallow the "wrote ..." lines the fixture builders print."""
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        yield


# --------------------------------------------------------------------------

def test_the_reader_understands_a_real_export(model):
    """Skin, animation and an embedded PNG texture all survive the round trip."""
    triangles = sum(len(p.indices) // 3 for _n, _s, p in model.primitives)
    check(triangles == 96, "expected 96 triangles, got %d" % triangles)
    check([a.name for a in model.animations] == ["Idle", "Walk"],
          "animations came back as %s" % [a.name for a in model.animations])
    check(all(near(a.duration, 1.0) for a in model.animations),
          "animation durations are wrong")
    texture = model.materials[0].texture
    check(texture is not None and texture.w == 4 and texture.h == 1,
          "the embedded PNG texture did not decode")
    check(model.materials[0].texture_error is None,
          "texture reported an error: %s" % model.materials[0].texture_error)

    # The skin has to actually move something: the same joint at two times in
    # the walk must put its vertices in different places.
    a = model.pose("Walk", 0.0)
    b = model.pose("Walk", 0.25)
    moved = sum(1 for p, q in zip(a.verts, b.verts) if p != q)
    check(moved > 0, "the walk animation moved no vertices -- skinning is dead")
    check(len(a.verts) == len(b.verts), "posing changed the vertex count")


def test_the_camera_lands_on_this_project_s_diamond():
    """The ground plane must project exactly where a TileMapLayer puts a cell.

    This is the whole reason the baker is allowed near the art: if it disagrees
    with Iso about where a cell is, every sprite it makes stands in the wrong
    place, and no amount of looking at a contact sheet reveals it.
    """
    tw, th, _cw, _ch = pixel.geometry()
    basis = sprite_bake.camera_basis()
    for cx, cy in ((0, 0), (1, 0), (0, 1), (3, 2), (-2, 5)):
        px, py, _d = sprite_bake.project((cx, cy, 0.0), basis)
        want = pixel.cell_centre(cx, cy)
        check(near(px + tw / 2.0, want[0]) and near(py + th / 2.0, want[1]),
              "cell (%d,%d) projects to (%.2f,%.2f), Iso says %s"
              % (cx, cy, px, py, want))

    # A true dimetric camera, derived from the diamond rather than typed in.
    up = basis[2]
    check(near(up, math.sqrt(tw * tw - th * th) / math.sqrt(2.0)),
          "the height scale is not the camera's own cosine")
    # Higher ground draws higher on screen, and nearer ground wins the depth test.
    _x, y_low, d_low = sprite_bake.project((0, 0, 0.0), basis)
    _x, y_high, d_high = sprite_bake.project((0, 0, 1.0), basis)
    check(y_high < y_low, "raising a point did not move it up the screen")
    check(d_high > d_low, "raising a point did not bring it toward the camera")
    _x, _y, d_front = sprite_bake.project((1, 1, 0.0), basis)
    check(d_front > d_low, "a cell nearer the front did not win the depth test")


def test_an_untouched_model_faces_the_camera():
    """A -Z-forward export lands on `down`, the direction that shows a face."""
    opts = sprite_bake.Options()
    check(near(opts.forward_angle, sprite_bake.DIRECTION_ANGLE["down"]),
          "a -z model faces %.1f, not `down`" % opts.forward_angle)
    check(list(sprite_bake.DIRECTIONS) == list(packs.ACTOR_DIRECTIONS),
          "the baker and the pack validator disagree about direction order")


def test_clip_planning_maps_names_to_the_game_s_vocabulary(model):
    opts = sprite_bake.Options()
    clips = sprite_bake.plan_clips(model, opts)
    names = [c.name for c in clips]
    check(names[0] == "idle", "idle is not first (rows: %s)" % names)
    check(sorted(names) == ["idle", "walk"], "clips came out as %s" % names)
    for clip in clips:
        check(clip.frames >= 1, "clip '%s' has no frames" % clip.name)
        check(clip.fps > 0 or clip.frames == 1,
              "clip '%s' has %d frames and no frame rate" % (clip.name, clip.frames))
        check(clip.loop, "clip '%s' should loop" % clip.name)

    # Names the game has a meaning for are recognised; one-shots do not loop.
    check(sprite_bake.clip_name_for("Armature|CoyoteTrot", set()) == "trot",
          "a trot was not recognised")
    check(sprite_bake.clip_name_for("Attack01", set()) == "attack",
          "an attack was not recognised")
    check(sprite_bake.clip_name_for("wobble", set()) == "wobble",
          "an unknown animation lost its name")
    check(sprite_bake.clip_name_for("idle", {"idle"}) == "idle_2",
          "a second idle collided with the first")
    for one_shot in ("attack", "die", "hurt"):
        check(one_shot in sprite_bake.ONE_SHOT, "%s should not loop" % one_shot)


def test_a_bake_produces_a_placeable_sprite(model):
    """The output has to satisfy the actor manifest before anything sees it."""
    opts = sprite_bake.Options(supersample=2, colours=4, max_frames=2)
    sheet, actor, notes = sprite_bake.bake(model, opts, log=lambda *_a: None)
    fw, fh = actor["frame_size"]
    ax, ay = actor["anchor"]
    check(fw > 0 and fh > 0, "frame is %dx%d" % (fw, fh))
    check(0 <= ax < fw and 0 <= ay < fh,
          "anchor %s is outside its own %dx%d frame" % ((ax, ay), fw, fh))
    check(not notes, "the bake complained: %s" % notes)

    directions = len(actor["directions"])
    rows = len(actor["clips"]) * directions
    columns = max(c["frames"] for c in actor["clips"].values())
    check(sheet.w == columns * fw and sheet.h == rows * fh,
          "sheet is %dx%d, layout wants %dx%d"
          % (sheet.w, sheet.h, columns * fw, rows * fh))
    for name, clip in actor["clips"].items():
        check(clip["row"] + directions <= rows,
              "clip '%s' runs off the end of the sheet" % name)

    # Every direction must actually draw something, or a facing is invisible.
    for d, direction in enumerate(actor["directions"]):
        painted = _painted(sheet, 0, d * fh, fw, fh)
        check(painted > 20, "direction '%s' drew only %d pixels"
              % (direction, painted))
    return sheet, actor


def test_the_directions_really_are_the_grid_s(model):
    """Head-on views are narrow; broadside views are wide.

    `down_right` is straight down the screen and `up_left` straight up it, so
    those two see the animal end-on and must be the narrowest. If the yaw were
    off by a step this is the check that fails -- and it is not something a
    contact sheet makes obvious.
    """
    opts = sprite_bake.Options(supersample=2, colours=4, max_frames=1,
                               only_clips=["idle"])
    sheet, actor, _notes = sprite_bake.bake(model, opts, log=lambda *_a: None)
    fw, fh = actor["frame_size"]
    widths = {}
    for d, direction in enumerate(actor["directions"]):
        widths[direction] = _width(sheet, 0, d * fh, fw, fh)
    end_on = ("down_right", "up_left")
    broadside = ("down_left", "up_right")
    check(max(widths[d] for d in end_on) < min(widths[b] for b in broadside),
          "end-on views %s are not narrower than broadside %s: %s"
          % (end_on, broadside, widths))
    # Opposite directions see the same silhouette from the other side.
    for a, b in (("down", "up"), ("left", "right"), ("down_left", "up_right")):
        check(abs(widths[a] - widths[b]) <= 2,
              "'%s' and '%s' should mirror but are %d and %d wide"
              % (a, b, widths[a], widths[b]))


def test_a_malformed_actor_pack_is_reported(tmp):
    """Every way a bake can go wrong has to fail before an engine sees it."""
    directory = os.path.join(tmp, "broken")
    os.makedirs(directory, exist_ok=True)
    with quiet():
        pixel.Canvas(20, 20).save(os.path.join(directory, "sheet.png"))
    base = {
        "name": "broken", "source": "s", "author": "a", "license": "l",
        "sheet": "sheet.png", "cell_size": [10, 10], "anchor": [5, 9],
        "_dir": directory,
    }

    def issues(actor):
        manifest = dict(base)
        manifest["actors"] = {"thing": actor}
        return packs.actor_problems(manifest, "broken")

    good = {"sheet": "sheet.png", "frame_size": [10, 10], "anchor": [5, 9],
            "directions": ["down", "left"],
            "clips": {"idle": {"row": 0, "frames": 1, "fps": 0.0}}}
    check(not issues(good), "a sound actor was rejected: %s" % issues(good))

    for label, broken in (
        ("anchor outside the frame", {"anchor": [10, 9]}),
        ("an unknown direction", {"directions": ["down", "sideways"]}),
        ("no directions at all", {"directions": []}),
        ("no clips", {"clips": {}}),
        ("a clip with no frames", {"clips": {"idle": {"row": 0, "frames": 0}}}),
        ("more frames than columns",
         {"clips": {"idle": {"row": 0, "frames": 9, "fps": 8}}}),
        ("a row off the end of the sheet",
         {"clips": {"idle": {"row": 7, "frames": 1, "fps": 0.0}}}),
        ("frames with no frame rate",
         {"clips": {"idle": {"row": 0, "frames": 2}}}),
        ("a missing sheet", {"sheet": "nope.png"}),
    ):
        actor = dict(good)
        actor.update(broken)
        check(bool(issues(actor)), "%s was accepted" % label)

    # And a pack that says nothing about what its pixels are for.
    manifest = dict(base)
    check(any("neither" in p for p in packs.problems(manifest)),
          "a pack with no tiles and no actors was accepted")


def test_the_pipeline_will_not_guess_a_licence():
    for missing in ({}, {"author": "me"}, {"author": "me", "source": "s"}):
        try:
            inbox.check_credit("thing", "/tmp/thing.glb", missing)
            check(False, "credit %s was accepted" % missing)
        except inbox.Failure as exc:
            check("data/inbox.json" in str(exc) and "thing.json" in str(exc),
                  "the error does not say where to fix it: %s" % exc)
    inbox.check_credit("thing", "/tmp/thing.glb",
                       {"author": "a", "source": "s", "license": "l"})
    CHECKS[0] += 1


def test_bad_settings_are_caught_before_a_long_bake():
    for bad, expect in (({"bake": {"nonsense": 1}}, "unknown bake setting"),
                        ({"bake": {"forward": "sideways"}}, "forward must be")):
        try:
            inbox.bake_options(bad)
            check(False, "%s was accepted" % bad)
        except inbox.Failure as exc:
            check(expect in str(exc), "unhelpful error: %s" % exc)


def test_a_sidecar_is_found_beside_its_asset(tmp):
    """foo-bar.glb takes its settings from foo-bar.json, not from its slug."""
    path = os.path.join(tmp, "some-model.glb")
    open(path, "wb").close()
    with open(os.path.join(tmp, "some-model.json"), "w") as f:
        f.write('{"license": "from-the-sidecar"}')
    out = inbox.settings_for("some-model", path, {"defaults": {"license": "L"}})
    check(out["license"] == "from-the-sidecar",
          "the sidecar beside the asset was not read")
    check(inbox.slug("example-quadruped.glb".split(".")[0]) == "example-quadruped",
          "slug mangled a hyphen: %s" % inbox.slug("example-quadruped"))


def test_settings_layer_in_the_documented_order():
    settings = {
        "defaults": {"_comment": "x", "author": "A", "license": "L",
                     "bake": {"_comment": "y", "colours": 8, "forward": "-z"}},
        "assets": {"thing": {"license": "M", "bake": {"colours": 12}}},
    }
    out = inbox.settings_for("thing", "/tmp/thing.glb", settings)
    check(out["author"] == "A", "defaults were lost")
    check(out["license"] == "M", "the asset block did not win")
    check(out["bake"]["colours"] == 12, "the asset's bake block did not win")
    check(out["bake"]["forward"] == "-z", "a default bake key was lost")
    check(not any(k.startswith("_") for k in out),
          "comment keys leaked into the settings: %s" % sorted(out))
    check(not any(k.startswith("_") for k in out["bake"]),
          "comment keys leaked into the bake block")


def test_a_file_the_pipeline_cannot_read_says_so(tmp):
    path = os.path.join(tmp, "not-a-model.glb")
    with open(path, "wb") as f:
        f.write(b"this is not a GLB at all")
    try:
        glb.load(path)
        check(False, "a corrupt file loaded")
    except glb.ModelError as exc:
        check("gltf" in str(exc).lower() or "glb" in str(exc).lower(),
              "unhelpful error for a corrupt model: %s" % exc)


def test_the_matrix_maths_is_right():
    check(glb.mat_mul(glb.IDENTITY, glb.IDENTITY) == glb.IDENTITY,
          "identity * identity is not identity")
    m = glb.trs_matrix((1.0, 2.0, 3.0), (0.0, 0.0, 0.0, 1.0), (2.0, 2.0, 2.0))
    check(glb.mat_point(m, (1.0, 0.0, 0.0)) == (3.0, 2.0, 3.0),
          "translate+scale put the point in the wrong place")
    # A quarter turn about Y sends +X to -Z.
    half = math.sqrt(0.5)
    turn = glb.trs_matrix((0.0, 0.0, 0.0), (0.0, half, 0.0, half), (1.0, 1.0, 1.0))
    x, y, z = glb.mat_point(turn, (1.0, 0.0, 0.0))
    check(near(x, 0.0, 1e-6) and near(y, 0.0, 1e-6) and near(z, -1.0, 1e-6),
          "a quarter turn about Y gave (%.3f, %.3f, %.3f)" % (x, y, z))
    back = glb.mat_mul(glb.mat_invert(m), m)
    check(all(near(a, b, 1e-9) for a, b in zip(back, glb.IDENTITY)),
          "a matrix times its inverse is not identity")
    mid = glb.quat_slerp((0.0, 0.0, 0.0, 1.0), (0.0, half, 0.0, half), 0.5)
    check(near(math.sqrt(sum(v * v for v in mid)), 1.0, 1e-9),
          "slerp returned an unnormalised quaternion")


def test_the_grid_conversion_keeps_the_model_s_handedness():
    """A mirrored character is the kind of bug nobody spots until it ships."""
    x = sprite_bake.to_grid((1.0, 0.0, 0.0))
    y = sprite_bake.to_grid((0.0, 1.0, 0.0))
    z = sprite_bake.to_grid((0.0, 0.0, 1.0))
    det = (x[0] * (y[1] * z[2] - y[2] * z[1])
           - x[1] * (y[0] * z[2] - y[2] * z[0])
           + x[2] * (y[0] * z[1] - y[1] * z[0]))
    check(near(det, 1.0), "the glTF -> grid conversion mirrors the model (det %g)"
          % det)
    check(sprite_bake.to_grid((0.0, 1.0, 0.0))[2] == 1.0,
          "glTF's up axis did not become the grid's")


# --------------------------------------------------------------------------

def _painted(sheet, ox, oy, w, h):
    return sum(1 for y in range(h) for x in range(w)
               if sheet.get(ox + x, oy + y)[3] > 0)


def _width(sheet, ox, oy, w, h):
    columns = [x for x in range(w)
               if any(sheet.get(ox + x, oy + y)[3] > 0 for y in range(h))]
    return (max(columns) - min(columns) + 1) if columns else 0


def main():
    tmp = tempfile.mkdtemp(prefix="port-azure-pipeline-")
    try:
        with quiet():
            path = make_model.main(os.path.join(tmp, "quadruped.glb"))
        model = glb.load(path)

        test_the_reader_understands_a_real_export(model)
        test_the_camera_lands_on_this_project_s_diamond()
        test_an_untouched_model_faces_the_camera()
        test_clip_planning_maps_names_to_the_game_s_vocabulary(model)
        test_a_bake_produces_a_placeable_sprite(model)
        test_the_directions_really_are_the_grid_s(model)
        test_a_malformed_actor_pack_is_reported(tmp)
        test_the_pipeline_will_not_guess_a_licence()
        test_bad_settings_are_caught_before_a_long_bake()
        test_a_sidecar_is_found_beside_its_asset(tmp)
        test_settings_layer_in_the_documented_order()
        test_a_file_the_pipeline_cannot_read_says_so(tmp)
        test_the_matrix_maths_is_right()
        test_the_grid_conversion_keeps_the_model_s_handedness()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    if FAILURES:
        print("\nFAILED  %d of %d checks in the pipeline suite"
              % (len(FAILURES), CHECKS[0]))
        for message in FAILURES:
            print("  x %s" % message)
        return 1
    print("PASSED  %d checks in the pipeline suite" % CHECKS[0])
    return 0


if __name__ == "__main__":
    sys.exit(main())
